Update 500_sysctl_rp_filter.sh
weka/wekachecker pull request #100
Opened 2024-05-10 19:10 UTC by vrragosta

Remove Python dependency.

Fix logic flaw when comparing "all" and specific interface values.

2024-05-10 19:19 UTC, vince-weka requested changes
The script must return some kind of text in addition to the return code.

The IF statements should have "else" clauses that echo something and set RETURN_CODE.

2024-05-10 19:26 UTC, vince-weka requested changes
Line 48... needs an 'else'

2024-05-16 14:16 UTC, vrragosta commented
> Line 48... needs an 'else'

Fixed.

2024-05-16 20:53 UTC, vince-weka approved these changes

2024-05-16 20:53 UTC, merged